## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  # - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

# uncomment and modify the following lines to manually install system packages
# addons:
 # apt: # apt-get for linux
 #   packages:
 #   - gfortran

# before_install:
#   - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
#   - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gcc; fi

## uncomment the following lines to override the default test script
# script:
#  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("NeighbourLists"); Pkg.test("NeighbourLists"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  # - julia -e 'using Pkg; cd(Pkg.dir("NeighbourLists")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  # - julia -e 'using Pkg; cd(Pkg.dir("NeighbourLists")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
